### ISSUE TITLE
Visual Studio Designer Issue (with workaround)

### ISSUE THREAD

**Issue by delinx32** [MrJul/Estragonia#2]
The designer appears to be looking for the output of the ExportDebug configuration regardless of what configuration is selected.  

When in "Debug" the following appears in the avalonia output window:

08:42:02.229 [Information] 0 Starting previewer process for '"C:\xxx\.godot\mono\temp\bin\ExportDebug\GREM.dll"'
08:42:02.233 [Information] 18532 Started previewer process for '"xxx\.godot\mono\temp\bin\ExportDebug\GREM.dll"'. Waiting for connection to be initialized.

The helloWorld example has the same issue:
08:56:28.443 [Information] 0 Starting previewer process for '"xxx\Estragonia\samples\HelloWorld\.godot\mono\temp\bin\ExportDebug\HelloWorld.dll"'

A normal avalonia project appears to check the correct configuration:
08:54:22.145 [Information] 0 Starting previewer process for '"xxx\AvaloniaApplication1\AvaloniaApplication1.Desktop\bin\Debug\net7.0\AvaloniaApplication1.Desktop.dll"'

Switching configurations and working in "ExportDebug" allows it to work normally.  I'm not sure of the origin of "ExportDebug".  It's not a configuration I added to the project.  It does not exist in an avalonia ui project created normally.

The helloworld example designer didn't work because it couldn't find "avalonia.png".  It did work when I ran it, and after some investigation, the fix was to add a / to the image source:
`
				<Image
					Source="/Avalonia.png"
					Width="64"
					Height="64"
					VerticalAlignment="Center"
					Grid.Column="0" />
`

**Comment by MrJul** [comment]
Of course I re-opened all GameMenu views but not the only HelloWorld one :)
The HelloWorld works fine on AvaloniaRider with the relative Avalonia.png path, but not on AvaloniaVS, that's a bit weird. Changing that to an absolute path for now, thanks.

`ExportDebug` and `ExportRelease` are added automatically by the Godot SDK. (I don't know why it doesn't use the standard Debug/Release.)

With `AvaloniaVS`, I think you're hitting https://github.com/AvaloniaUI/AvaloniaVS/issues/190: the extension takes the first configuration instead of the active one.

**Comment by delinx32** [comment]
OK, thanks.  I'll close this.  That does appear to be the issue.  Thank you for your work on this project.  It will be very useful.
